sudo: false

language: node_js

node_js:
  - "lts/*"

services:
  - postgresql

before_script:
  - psql -c "create database automart;" -U postgres

script:
  - npm run db:populate
  - npm test

after_success: 
 - npm run coverage